spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:./data/testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:h2:./data/testdb
    user: sa
jwt:
  header: Authorization
  secret: dHlyYW5vdHlyYW5vLW9obXlnaXJsLWNoaWNrZW4tcGl6emEtc3Rha2Utd2luZS12b2x2by1rb3JlYS1kZXZlbG9wZXItcnVuLWxvdmUtcGVhY2UtcmVjb3JkLXNpbmctdG9nZXRoZXI= # tyranotyrano-ohmygirl-chicken-pizza-stake-wine-volvo-korea-developer-run-love-peace-record-sing-together 을 base64 로 Encoding 한 값
  access-token-validity-in-millisecond: 60000       # 1분
  refresh-token-validity-in-millisecond: 300000  # 5분

# 콘솔에 출력되는 JPA SQL 중 "?" 에 들어간 파라미터값 로그 출력
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
