spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:./data/testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
jwt:
  header: Authorization
  secret: jwtsecretkey
  access-token-validity-in-millisecond: 60000       # 1분
  refresh-token-validity-in-millisecond: 300000  # 5분

logging:
  level:
    root: debug
    org.hibernate.SQL: debug